version: '3.6'

services:
  shutterstock:
    build: ./docker/web/.
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - PARSER_JSON_LIMIT=${PARSER_JSON_LIMIT}
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - ./:/robotBase
    working_dir: /robotBase
    command: sh -c "npm install -g npm@9.3.1 && npm install && npm run build && cd dist && node server.js"
    container_name: shutterstock
