version: '3.6'

services:
  shutterstock:
    build:
      context: .
      args:
          HTTP_PORT: ${HTTP_PORT}
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - PARSER_JSON_LIMIT=${PARSER_JSON_LIMIT}
      - QUEUE_URI_MONITOR=${QUEUE_URI_MONITOR}
      - QUEUE_DEFAULT=${QUEUE_DEFAULT}
      - IMAGE_TEMP_DIR=/temp_images
      - APP_PATH=/robotBase
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "5859:5859"
    expose:
      - "${HTTP_PORT}"
    command: sh -c "cd dist && node server.js"
    container_name: shutterstock
